# Site settings
title: Peter Larson
email: peter@peterlarson.xyz
description: > # this means to ignore newlines until "baseurl:"
  Personal website for peter larson. 
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  peterlarson

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/Home/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/


